### ISSUE TITLE
I want to run this project

### ISSUE THREAD

**Issue by praba007** [Nzkhan/GST-BillingSystem#1]
Hii sir i want to import and run this project. But i don't know the procedure please send a procedure to prabagaranboss@gmail.com

**Comment by Nzkhan** [comment]
Hey @parab007 this project is still in the development process and its a commercial product for some of my clients , so be able to share the details

**Comment by Nzkhan** [comment]
Hey @parab007 this project is still in the development process and its a commercial product for some of my clients , so be able to share the details

**Comment by praba007** [comment]
Ok
